### ISSUE TITLE
I am running Linux Mint 20.1 and I cannot access to the serial port of Nano 33 BLE

### ISSUE THREAD

**Issue by tototek** [tinyMLx/appendix#3]
He followed his ArduinoFAQ.md step by step, installing Arduino 1.8.3. And following points 1.2.3 (dialout, chmod and modemmanager) for Linux Mint.
a- I want to load the sketch blink and the error is: No device found on ttyACM0
b-Using the same Arduino 1.8.3 and an Arduino Mega 2560 board I compile and load blink correctly with ttyACM0 !.
c-Using Windows 7 with Arduino 1.8.9 loading drivers for BLE nano 33, compile and load without problems, blink sketch and TensorFlow sketch that I train.
d-With these TensorFlow sketch loaded in Windows, I go back to Linux Mint and correctly see the data that we sent the sketch in the ttyACMo port without problems!

Apparently : Not Linux Mint problem.The problem is writing to NANO 33 and not in reading. Hope you can fix it.

**Comment by plancherb1** [comment]
Have you tried forcing boot loader mode before upload? (Double click the reset button). I’ve found the nano to sometimes be a bit temperamental with the Linux USB drivers.

**Comment by KlausPuchner** [comment]
@tototek This script might help: https://github.com/KlausPuchner/TinyML/tree/main/00_arduino_installer/nano-33-ble-sense

**Comment by plancherb1** [comment]
Awesome thanks @KlausPuchner --- @tototek let me know if that solved your problem and I'll close the issue!

**Comment by tototek** [comment]
Thanks @KlausPuchner and @plancherb1 .I have installed the script.The script is awesome but the error No device found on ttyACM0 persist. Another strange thing: when I ask for information from the board, it brings me the correct VID, PID and SN data.

**Comment by plancherb1** [comment]
Have you tried re-selecting the port again right before upload? I’ve found that the Nano port-hops a lot.

**Comment by tototek** [comment]
Yes I do.

**Comment by tototek** [comment]
When I use the GTKTerm, I correctly read the gyroscope data that the nano sends me !.(That sketch I loaded in Windows).

**Comment by plancherb1** [comment]
Wow how strange -- my best guess at this point is that there is a weird USB driver issue with the Nano and Arduino and Linux Mint (I can't recreate this on Ubuntu -- I tried). So 1) I think you should raise this as an issue to Arduino and 2) I will keep digging and if I come up with any other ideas I'll let you know!

**Comment by tototek** [comment]
Thanks for the help @plancherb1 .I did another test with VSC and Platformio and it loads the sketches without problems, but ...............
Now when loading the new sketches it does not delete the flash, therefore the same sketch is always loaded. Too much trouble for me!
I agree that it is a problem with the Arduino IDE only ,no Linux,no Nano. Unfortunately I'll go back to Windows until something is fixed.

**Comment by plancherb1** [comment]
Sorry you’ve been having all these problems and hopefully Arduino resolves it soon!
